### ISSUE TITLE
use an argument parser instead of manually parsing 

### ISSUE THREAD

**Issue by Shacklebolt13** [Shacklebolt13/CertMan#1]
We're currently using manual parsing for command line args. Add an argument parser to do the same

**Comment by dinesh-07** [comment]
I can work on this, can you assign to me?

**Comment by Shacklebolt13** [comment]
Sure, assigned ✔️

**Comment by dinesh-07** [comment]
Fixed as part of https://github.com/Shacklebolt13/CertMan/pull/2
